### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by Un1xMida** [Frogmouth/jquery.tickerNews#1]
hey there , 
when i use the 
$("#T1").hover(
  function(handlerIn) {$("#T1").stopTicker();},function(handlerOut) {$("#T1").newsTicker();}
);
the loop destroyed :confused:  any help ? :open_mouth:

**Comment by Frogmouth** [comment]
Hi, unfortunately right now there aren't an easy way to "Pause" and "Resume" the animation of the ticker.
I'm so sorry, but right now I have no time to build one.

**Comment by Un1xMida** [comment]
well thanks anyway :laughing:

**Comment by Frogmouth** [comment]
If I have freetime this weekend, I can try to find a solution. But It isn't a promise.
Sorry mate...

**Comment by Frogmouth** [comment]
Hi Mate!
I commit a new release when i implement PAUSE and RESUME, it's a beta feature but you can use it, it works.

Bye
