### ISSUE TITLE
Change Time

### ISSUE THREAD

**Issue by RationalRabbit** [Frogmouth/jquery.tickerNews#11]
I hope that, since this is a simple question, you won't mind answering.
I need to change the time. I have an input and an onChange function. But it doesn't work. Can you help? 
I am replacing the data because I thought that would help. Data replaces fine but time does not change: I need to stop and restartt, I guess, but I don't know how.
```
  $("#TickTime").on('change',function()
   {
      TickTime = $("#TickTime").val();
      $.ajax(
      {
         type: 'POST',
         url: 'GetTicks.php',
         dataType: 'HTML',
         success: function(data,status)
         {
            $(".ti_content").html(data);
            _Ticker = $(".TickerNews").newsTicker(
            {
               base :
               {
                  width : 2100,
                  time : TickTime
               }
            });
         }
      });
   });
```
If you wouldn't mind, it would be greatly appreciated. I'm not real good at JavaScript or jQuery. I have been pouring over your js file and experimenting for some time with no luck.

**Comment by Frogmouth** [comment]
Hello!
I will try to investigate your needed, could you please descrive to me your functional needed?
Seems that you need to call a PHP API that return an HTML that you use like content of the news ticker?

please could you post a simple HTML returned by your PHP?

**Comment by Frogmouth** [comment]
Hello "Rabbit" (eheh),

Like fast resolution you could try to use this code:

```
var $ticker = $(".TickerNews");
$("#TickTime").on('change',function()
   {
      TickTime = $("#TickTime").val();
      $.ajax(
      {
         type: 'POST',
         url: 'GetTicks.php',
         dataType: 'HTML',
         success: function(data ,status)
         {
            $ticker.newsTickerPause();
            $ticker.find(".ti_content.ti_clone").remove();
            $ticker.find(".ti_content").removeAttr("style").html(data);
            _Ticker = $ticker.newsTicker(
            {
               base :
               {
                  width : 2100,
                  time : TickTime
               }
            });
         }
      });
   });
```

Simply the code "pause" the ticker (clear the timeloop), remove the cloned content created for the infinite scroll, replace the content and re-init the ticker.

Let me know if it works.
Simone

**Comment by RationalRabbit** [comment]
You just made my day Frogmouth! Works perfectly. Thank you so much.

**Comment by Frogmouth** [comment]
You are welcome, mate.
I know how frustrate is this work 👯 
I will try to include this function in the core.

This plugin is very old, so, I suggest you to test it with some different browser and device to see if all works.

Regards,
Simone

**Comment by RationalRabbit** [comment]
Works fine with jQuery 3.4.1. on IE 11 and Edge, FireFox 76.0.1, Brave 1.9.72, and Chrome 83.0.4103.61. Will send you a link when this site is live. Store the data in a db. This code is an editing utility so the client can keep it current. And what you showed me works really quick. as soon as the field is exited, the ticker speed changes. Nice.
