### ISSUE TITLE
please help me : Maximum call stack size exceeded error 

### ISSUE THREAD

**Issue by thangkj** [Frogmouth/jquery.tickerNews#2]
please help me : Maximum call stack size exceeded error

**Comment by Frogmouth** [comment]
when this error occurred? I need more information to help you.

**Comment by thangkj** [comment]
when I use less than three class ti_news , error : Maximum call stack size exceeded error

**Comment by Frogmouth** [comment]
Hi mate!
I found the bug.
It occurs every time that the ticker's content length is less then the container width.
I Commit an update, takes a look and tries with this code.

Simone

**Comment by thangkj** [comment]
thank you!
