### ISSUE TITLE
Pause on hover

### ISSUE THREAD

**Issue by 2a5A1Ghu1** [Frogmouth/jquery.tickerNews#4]
Instead of stop button there the scroll should have an option to stop scrolling on hover

**Comment by Frogmouth** [comment]
Hi Budilla,

you can do it yourself using:

```
<div class="TickerNews" id="T1">
   <div class="ti_wrapper">
       [...]
   </div>
</div>
```

```
var _Ticker = $("#T1").newsTicker();
_Ticker.on("mouseenter",function(){
    this.pauseTicker();
    //take care, use "this" not "$(this)"
});
_Ticker.on("mouseleave",function(){
    this.startTicker();
});
```

Try this and tell me if it is what you need.

**Comment by 2a5A1Ghu1** [comment]
Thanks for the help and I am not well versed in javascript so I am having problems trying to plug the above in. Or I am doing something wrong. In either case it errors on me, stops the marquee from running or the marquee run even on hover. here is how I am using it http://www.thedailygoblin.com/

**Comment by Frogmouth** [comment]
Hi mate,

take a look to my new commit.
I add a new example with working code that pause and resume the ticker on `mouseover`: [(Go to code)](https://github.com/Frogmouth/jquery.tickerNews/blob/master/example/index_pause-onhover.html)

**Comment by 2a5A1Ghu1** [comment]
SOLVED: Thank you for your help.
