### ISSUE TITLE
Continous scroll

### ISSUE THREAD

**Issue by TripwireNL** [Frogmouth/jquery.tickerNews#5]
Hi,

Does this plugin supports continuous scroll? I'm using the ticker to show news from an RSS feed but every time the ticker stops scrolling after a while and then reappears. 
My code: (CSS is the same as yours)
`$(".TickerNews").newsTicker({
       itemWidth:  'auto',
       wrapper:    '.ti_wrapper',
       slide:      '.ti_slide',
       content:    '.ti_content'
});`

and HTML:
`<div class="TickerNews default_theme_3" id="T2">
                        <div class="ti_wrapper">
                            <div class="ti_slide">
                                <div class="ti_content">
                                    <div class="ti_news" data-ng-repeat="feed in newsEntries">
                                        <a data-ng-href="{{feed.link}}" target="_blank">{{feed.title}} &nbsp; | &nbsp;</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>`

**Comment by Frogmouth** [comment]
Hi mate, normally the ticker is infinite without stops. How many news are rendered inside ticker? the ticker "stops" when you scroll the window, when the last news is shown or in all cases? can you reproduce the problem here: https://jsfiddle.net?

**Comment by Frogmouth** [comment]
Hi mate! this issue is older then 25 days without response, i close it.
If you need some help please open an other issue.
