### ISSUE TITLE
Scroll Falls out of Contianer

### ISSUE THREAD

**Issue by 2a5A1Ghu1** [Frogmouth/jquery.tickerNews#6]
If viewport is wider that amount of text in ticker and ticker is set to 100% of viewport width the scrolling text falls out of it's container.

Possible fix is to repeat text if text is smaller than viewport width.

**Comment by Frogmouth** [comment]
Hi @buddilla can show me a page (even in https://jsfiddle.net/), where the problem is reproduced?
I try but if you have one i can make the fix more faster.

**Comment by Frogmouth** [comment]
Download the new version i fix the issue, try and tell me!
